project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



